[package]
name = "audiorust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
realfft = "3.3.0"
rustfft = "6.2.0"
